# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

commands:
  set_region:
    steps:
      - run: aws configure set region ap-northeast-2

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - set_region 
      - run:
          name: run bucket.yml file to create/update stack for new S3.
          command: >-
            aws cloudformation deploy
            --template-file bucket.yml
            --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" 
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: "Retrieve last production deployment ID using list-exports function"
          command: >-
            aws cloudformation list-exports
            --query "Exports[?Name==\`PipelineID\`].Value"
            --no-paginate 
            --output text
      - persist_to_workspace:
          root: .
          paths:
            - text

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - set_region
      - run:
          name: Deploy using same stack with new pipelineID
          command: >-
            aws cloudformation deploy
            --template-file cloudfront.yml
            --stack-name production-distro
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - set_region
      - attach_workspace:
          at: .
      - run:
          name: Remove old version S3 bucket.
          command: aws s3 rm "s3://lastproductionbucket.s3.amazonaws.com" --recursive
      - run:
          name: Delete new stack which was made for production testing
          command: >-
            aws cloudformation delete-stack
            --stack-name "$(<text)"

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      #- welcome/run
      - create_and_deploy_front_end
      - get_last_deployment_id:
          requires:
            - create_and_deploy_front_end
      - promote_to_production:
          requires:
            - get_last_deployment_id
      - clean_up_old_front_end:
          requires:
            - promote_to_production
